version: '3.9'
services:
  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: ${MASTER_DB_PASSWORD}
      POSTGRES_USER: ${MASTER_DB_USER}
      POSTGRES_DB: ${MASTER_DB_NAME}
    env_file:
      - ./.env
    ports:
      - 5432:5432

  app:
    build: ./app
    restart: always
    ports:
      - 5000:5000
    volumes:
    - ./app:/app
    env_file:
    - .env
